Запись матрицы в коде

In [3]:
import numpy as np

m = np.array([
      [2, 17, 43],
      [36, 8, 4],
      [10, -11, 6],
      [3, 7, 15]
    ])

k = np.array([
    [1],
    [14],
    [6],
    [9]
    ])
print("Матрица:")  # Вывод подписи на экран.
print(m)
print()  # Пустая строка для разделения.
print("Вектор-столбец:")  # Вывод подписи на экран.
print(k) 

Матрица:
[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]

Вектор-столбец:
[[ 1]
 [14]
 [ 6]
 [ 9]]


In [4]:
# Транспонированная матрица
m = np.array([
    [2, 17, 43],
    [36, 8, 4],
    [10, -11, 6],
    [3, 7, 15]
    ])
print("Матрица:")
print(m)  # Вывод исходной матрицы.
print()  # Пустая строка для разделения.
m = m.T  # Теперь m - это транспонированная матрица.
print("Транспонированная матрица:")
print(m)  # Вывод новой, транспонированной матрицы. 

Матрица:
[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]

Транспонированная матрица:
[[  2  36  10   3]
 [ 17   8 -11   7]
 [ 43   4   6  15]]


In [5]:
# Упражнение 4
import numpy as np

# данные:
m = np.array([
    [24, 48, 6],
    [-2, 11, 0.7],
    [9, 1, 14]
])

# допишите код здесь
print("Матрица:")
print(m)
print()
# допишите код здесь
print("Транспонированная матрица:")
print(m.T)

Матрица:
[[24.  48.   6. ]
 [-2.  11.   0.7]
 [ 9.   1.  14. ]]

Транспонированная матрица:
[[24.  -2.   9. ]
 [48.  11.   1. ]
 [ 6.   0.7 14. ]]


In [6]:
# Задача 5
import numpy as np

# Данные для матрицы d:
# 8, 7, 11
# 14, 5, 0
# 0, 10, 12

# ваш код здесь
d = np.array([
    [8, 7, 11],
    [14, 5, 0],
    [0, 10, 12]
    ])

print("Матрица растений дедушки:")
print(d)

Матрица растений дедушки:
[[ 8  7 11]
 [14  5  0]
 [ 0 10 12]]


In [7]:
# Задача 6
import numpy as np

S = np.array([[4, 7, 9], [-2, 8, 15]])
print("Матрица S:")
print(S)

print("Транспонированная матрица S:")
print(S.T)

print("Транспонированная дважды матрица S:")
print(S.T.T) 

Матрица S:
[[ 4  7  9]
 [-2  8 15]]
Транспонированная матрица S:
[[ 4 -2]
 [ 7  8]
 [ 9 15]]
Транспонированная дважды матрица S:
[[ 4  7  9]
 [-2  8 15]]


Эмма планирует отдых в Петербурге с 
20
20 мая по 
27
27 мая и смотрит, какая будет погода. Данные о каждом дне представлены по порядку в следующем виде:
Температура воздуха днём, градусы	Температура воздуха ночью, градусы	Максимальная скорость ветра, м/с
В отдельных строчках в таком же порядке выведите с помощью индексации:
Температуру воздуха днём 
24
24 мая.
Скорость ветра 
21
21 мая.
Данные о погоде 
26
26 мая.
Температуру воздуха ночью в каждую из дат поездки.

In [ ]:
import numpy as np

spb = np.array([
        [13, 3, 6],
        [12, 3, 9],
        [14, 3, 9],
        [18, 4, 5],
        [18, 8, 5],
        [20, 10, 7],
        [19, 12, 10],
        [19, 12, 8],
    ])

print('Температура воздуха днём 24 мая:')
print(spb[4, 0]) # добавьте свой код

print('Скорость ветра 21 мая:')
print(spb[1, 2]) # добавьте свой код

print('Данные о погоде 26 мая:')
print(spb[-2, :]) # добавьте свой код

print('Температуры воздуха ночью в каждую из дат:')
print(spb[:, 1]) # добавьте свой код

Температура воздуха днём 24 мая:
18
Скорость ветра 21 мая:
9
Данные о погоде 26 мая:
[12  3  9]
Температуры воздуха ночью в каждую из дат:
[13 12 14 18 18 20 19 19]


#### Урок 4 умножение матриц на скаляр, сложение матриц

![](img/2026-02-24_11-28-32.png)

In [3]:
# sample
import numpy as np

week_1 = np.array([
        [5, 20, 11, 21],
        [8, 35, 9, 3],
        [4, 16, 12, 5],
        [2, 28, 8, 7],
        [11, 34, 4, 8],
        [7, 56, 0, 2],
        [9, 8, 5, 9],
    ])
week_2 = np.array([
        [32, 15, 8, 22],
        [0, 28, 7, 17],
        [3, 24, 6, 9],
        [10, 19, 8, 32],
        [17, 40, 30, 27],
        [20, 70, 40, 33],
        [8, 14, 21, 6],
    ])
week_1_2 = week_1 + week_2
print(week_1_2)
print("==================")
hypothesis = 3 * week_1_2
print(hypothesis)

[[ 37  35  19  43]
 [  8  63  16  20]
 [  7  40  18  14]
 [ 12  47  16  39]
 [ 28  74  34  35]
 [ 27 126  40  35]
 [ 17  22  26  15]]
[[111 105  57 129]
 [ 24 189  48  60]
 [ 21 120  54  42]
 [ 36 141  48 117]
 [ 84 222 102 105]
 [ 81 378 120 105]
 [ 51  66  78  45]]


In [4]:
# Произведение Адамара
a = np.array([
    [2, 7],
    [5, 6]
])
b = np.array([
    [8, 1], 
    [2, 4]
])
print(a * b) 

[[16  7]
 [10 24]]


In [5]:
#  упражнение 5 

K = np.array([
    [0, 29],
    [-6, 11]
])
S = np.array([
    [24, 0],
    [-16, 8]
])
Z = np.array([
    [44, 88],
    [11, -121]
])

R = -2 * K + 0.3 * S.T - 0.05 * S.T - Z / 11
print(R)


[[  2. -70.]
 [ 11.  -9.]]


In [ ]:
# Задача 6 
prices = np.array([
[85312, 77000, 68000],
 [9600, 8800, 12812],
 [7200, 20440, 15645]
])
new_prices = prices / 1.5
print(new_prices)

In [ ]:
# Задача 7

# Данные:
first = np.array([
    [6, 40],
    [8, 1000],
    [1.2, 600]
])

second = np.array([
    [2, 63],
    [4, 200],
    [2, 500]
])

third = np.array([
 [0.5, 62],
 [3, 300],
 [3, 400]]
])

fourth = np.array([
 [0.3, 23],
 [5, 300],
 [1, 300]
])

result = first + second + third + fourth    
print(result)

In [ ]:
# Задача 8

A = np.array([
    [5, -7, 0.55],
    [-2, -15, 2.7],
    [3, 0.6, 14]
])

B = np.array([
    [17, -9, 26],
    [0.5, -3, 2.7],
    [0.6, 3.14, -9]
 ])

C = np.array([
    [29, -5, 38],
    [0.8, -4.9, 6],
    [11.7, -4, 5]
])

R = 3 * A - 2 * B + C.T

print(R)