In [8]:
# Определите, какое произведение возможно, и преобразуйте векторы в необходимые матрицы

import numpy as np

r = np.array([[2, 18, 7],
              [-5, 4, 8]])
d = np.array([11, -6])
h = np.array([-10, 0, 29])


d_row = d.reshape(1, 2)
h_row = h.reshape(3, 1)
print("Произведение матрицы R и вектора d:")
print(d_row @ r)
print() # пустая строка
print("Произведение матрицы R и вектора h:")
print(r @ h_row)

Произведение матрицы R и вектора d:
[[ 52 174  29]]

Произведение матрицы R и вектора h:
[[183]
 [282]]


Задача 6

Таня, маркетолог косметического магазина, проектирует линейку подарочных наборов. Цена такого набора должна составлять 
80% 80% от суммы, за которую продавались бы все те же самые товары вместе, но вне набора.
Состав каждого набора указан в таблице, цены на отдельные продукты — в векторе цен.
Напишите программу для вычисления стоимости каждого набора.

In [14]:
# Найдите первоначальную стоимость каждого набора и умножьте на 0.8.

import numpy as np


a = np.array([
    [1, 1, 1, 0, 0],
    [1, 1, 0, 1, 0],
    [0, 1, 0, 0, 1],
    [0, 0, 1, 0, 2]])
p = np.array([630, 1030, 1350, 1550, 480])

p_col = p.reshape(5, 1)
full_cost = a @ p_col


result = full_cost * 0.8

print(result)

[[2408.]
 [2568.]
 [1208.]
 [1848.]]


Результат - столбец. Стоит рассматривать его как столбец, добавляемый в таблицу, тогда понятно почему проводится reshape

In [11]:
(630 + 1030 + 1350) * 0.8

2408.0

Напишите программу для вычисления произведений 
KS, RS, RKS, SKR.

Если какое-то из них невозможно, вместо него запишите print("no").

In [ ]:
import numpy as np

k = np.array([
    [4, 8, 0, 12, 3],
    [2, 8, -6, 9, 1],
    [7, 6, 1, 0, 10]
    ])
r = np.array([
    [8, 0, 1, 3, 9],
    [-2, 7, 9, 1, 4],
    [6, 3, 6, -7, 1],
    [0, 12, 6, 3, 7],
    [2, 8, 12, 21, 5],
])
s = np.array([
    [1, 6, 9],
    [2, 15, 5],
    [8, 0, 12],
    [4, 7, 3],
    [1, 6, 14]
])

# Ваш код здесь
ks = k @ s

rs = r @ s

skr = s @ k @ r

print("Произведение KS:")
print(ks)
print()
print("Произведение RS:")
print(rs)
print()
print("Произведение RKS:")
print('no')
print()
print("Произведение SKR:")
print(skr)