Запись матрицы в коде

In [3]:
import numpy as np

m = np.array([
      [2, 17, 43],
      [36, 8, 4],
      [10, -11, 6],
      [3, 7, 15]
    ])

k = np.array([
    [1],
    [14],
    [6],
    [9]
    ])
print("Матрица:")  # Вывод подписи на экран.
print(m)
print()  # Пустая строка для разделения.
print("Вектор-столбец:")  # Вывод подписи на экран.
print(k) 

Матрица:
[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]

Вектор-столбец:
[[ 1]
 [14]
 [ 6]
 [ 9]]


In [4]:
# Транспонированная матрица
m = np.array([
    [2, 17, 43],
    [36, 8, 4],
    [10, -11, 6],
    [3, 7, 15]
    ])
print("Матрица:")
print(m)  # Вывод исходной матрицы.
print()  # Пустая строка для разделения.
m = m.T  # Теперь m - это транспонированная матрица.
print("Транспонированная матрица:")
print(m)  # Вывод новой, транспонированной матрицы. 

Матрица:
[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]

Транспонированная матрица:
[[  2  36  10   3]
 [ 17   8 -11   7]
 [ 43   4   6  15]]


In [5]:
# Упражнение 4
import numpy as np

# данные:
m = np.array([
    [24, 48, 6],
    [-2, 11, 0.7],
    [9, 1, 14]
])

# допишите код здесь
print("Матрица:")
print(m)
print()
# допишите код здесь
print("Транспонированная матрица:")
print(m.T)

Матрица:
[[24.  48.   6. ]
 [-2.  11.   0.7]
 [ 9.   1.  14. ]]

Транспонированная матрица:
[[24.  -2.   9. ]
 [48.  11.   1. ]
 [ 6.   0.7 14. ]]


In [6]:
# Задача 5
import numpy as np

# Данные для матрицы d:
# 8, 7, 11
# 14, 5, 0
# 0, 10, 12

# ваш код здесь
d = np.array([
    [8, 7, 11],
    [14, 5, 0],
    [0, 10, 12]
    ])

print("Матрица растений дедушки:")
print(d)

Матрица растений дедушки:
[[ 8  7 11]
 [14  5  0]
 [ 0 10 12]]


In [7]:
# Задача 6
import numpy as np

S = np.array([[4, 7, 9], [-2, 8, 15]])
print("Матрица S:")
print(S)

print("Транспонированная матрица S:")
print(S.T)

print("Транспонированная дважды матрица S:")
print(S.T.T) 

Матрица S:
[[ 4  7  9]
 [-2  8 15]]
Транспонированная матрица S:
[[ 4 -2]
 [ 7  8]
 [ 9 15]]
Транспонированная дважды матрица S:
[[ 4  7  9]
 [-2  8 15]]


In [ ]:
import numpy as np

spb = np.array([
        [13, 3, 6],
        [12, 3, 9],
        [14, 3, 9],
        [18, 4, 5],
        [18, 8, 5],
        [20, 10, 7],
        [19, 12, 10],
        [19, 12, 8],
    ])

print('Температура воздуха днём 24 мая:')
print(spb[4, 0]) # добавьте свой код

print('Скорость ветра 21 мая:')
print(spb[1, 2]) # добавьте свой код

print('Данные о погоде 26 мая:')
print(spb[-2, :]) # добавьте свой код

print('Температуры воздуха ночью в каждую из дат:')
print(spb[:, 1]) # добавьте свой код

Температура воздуха днём 24 мая:
18
Скорость ветра 21 мая:
9
Данные о погоде 26 мая:
[12  3  9]
Температуры воздуха ночью в каждую из дат:
[13 12 14 18 18 20 19 19]
