In [1]:
import numpy as np

a = np.array([
    [0, 17, -2, 6],
    [7, 2, 15, 4],
    [5, -8, 3, 6],
    [0, -12, 4, 7]
])
t = np.array([8, -4, 1, 15])
t_column = t.reshape(4, 1)
a_inv = np.linalg.inv(a)

s = a_inv.dot(t_column)
check = a.dot(s)

print("Прообраз:")
print(s)
print("Проверка:")
print(check)

Прообраз:
[[-2.29187817]
 [-0.10862944]
 [ 0.34873096]
 [ 1.75736041]]
Проверка:
[[ 8.]
 [-4.]
 [ 1.]
 [15.]]


In [2]:
import numpy as np

a = np.array([
    [0, 17, -2, 6],
    [7, 2, 15, 4],
    [5, -8, 3, 6],
    [0, -12, 4, 7]
])
s = np.array([6, 3, 2, 9])

s_column = s.reshape(4, 1)
v = a @ s_column

check = np.linalg.inv(a) @ v

# Допишите код здесь.

print("Образ:")
print(v)
print("Проверка:")
print(check)

Образ:
[[101]
 [114]
 [ 66]
 [ 35]]
Проверка:
[[6.]
 [3.]
 [2.]
 [9.]]


In [ ]:
# Данные для копирования
# 3, -1, 3
# 2, -2, 1
# 2, 5, 2

import numpy as np

a = np.array([
    [1, 3, 1],
    [-1, 1, 1],
    [1, 4, 1]
])
# Допишите код здесь
t = np.array([
    [3, 2, 2],
    [-1, -2, 5],
    [3, 1, 2]
])

s = np.linalg.inv(t)

print((s @ a @ t).round())

[[-1.  4. -2.]
 [ 1. -0.  1.]
 [ 5. -5.  4.]]
