In [1]:
import numpy as np

a = np.array([
    [0.55, 0.4, 1.2, 6],
    [-12, -9, 0.5, 1],
    [8.8, -8, -4, 2.9],
    [1.3, 7, -0.94, 2]
])

# Допишите код здесь.

print("Матрица:")
print(a)
print("Обратная матрица:")
# Пожалуйста, сохраните обратную матрицу в переменной b
b = np.linalg.inv(a)
print(b)
print("Проверка единичной матрицей:")
print((a @ b).round())

Матрица:
[[  0.55   0.4    1.2    6.  ]
 [-12.    -9.     0.5    1.  ]
 [  8.8   -8.    -4.     2.9 ]
 [  1.3    7.    -0.94   2.  ]]
Обратная матрица:
[[ 0.03064619 -0.07713982  0.0183436  -0.07996688]
 [-0.01615125 -0.01149314 -0.02884959  0.09603222]
 [ 0.19152961 -0.12317838 -0.13254987 -0.32080232]
 [ 0.12662826  0.03247304  0.02675178  0.06508861]]
Проверка единичной матрицей:
[[ 1.  0. -0.  0.]
 [ 0.  1.  0. -0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


![alt text](image.png)

In [2]:
import numpy as np

a = np.array([
    [325, 81],
    [260, 60]
])
b = np.array([2599, 2060])
o = np.linalg.inv(a) # Вычисление обратной матрицы.
b_column = b.reshape(2, 1)
result = o @ b_column # Скалярное произведение.

print(result)

[[7.]
 [4.]]


In [4]:
#  Определитель

import numpy as np

# Данные:
a = np.array([
    [-0.8, 24],
    [1, 3.7]
])

# Допишите код здесь.
print("Матрица:")
print(a)
print("Определитель:")
det = np.linalg.det(a)
print(det)

Матрица:
[[-0.8 24. ]
 [ 1.   3.7]]
Определитель:
-26.960000000000004


In [ ]:
import numpy as np

a2 = np.array([-3, -2])    # Вектор а1
a1 = np.array([6, -3])     # Вектор а2
a = np.array([a1, a2])     # Матрица
det = np.linalg.det(a)     # Определитель матрицы

print("Матрица:")
print(a)
print("Определитель:")
print(det)

Матрица:
[[ 6 -3]
 [-3 -2]]
Определитель:
-21.0


In [1]:
import numpy as np

a = np.array([
    [1, 0, 3],
    [2, 4, 1],
    [7, 4, 3]
])
det_a = np.linalg.det(a)
b = np.array([
    [7, 11, -3, 5],
    [1, 8, -6, -4],
    [9, -2, 4, 25],
    [3, 8, 1, -7]
])
det_b = np.linalg.det(b)
c = np.array([
        [6, 1, -4, 5, 9],
        [2, 9, -0.3, 11, 6],
        [8, -4, 5, 2, 11],
        [-3, -8, 4, -5, 2],
        [9, -7, 4, -1, 0.5]
])
det_c = np.linalg.det(c)
print("Матрица:")
print(a)
print("Определитель:")
print(det_a)
print("Матрица:")
print(b)
print("Определитель:")
print(det_b)
print("Матрица:")
print(c)
print("Определитель:")
print(det_c)

Матрица:
[[1 0 3]
 [2 4 1]
 [7 4 3]]
Определитель:
-51.999999999999986
Матрица:
[[ 7 11 -3  5]
 [ 1  8 -6 -4]
 [ 9 -2  4 25]
 [ 3  8  1 -7]]
Определитель:
303.00000000000205
Матрица:
[[ 6.   1.  -4.   5.   9. ]
 [ 2.   9.  -0.3 11.   6. ]
 [ 8.  -4.   5.   2.  11. ]
 [-3.  -8.   4.  -5.   2. ]
 [ 9.  -7.   4.  -1.   0.5]]
Определитель:
-30765.799999999967


In [4]:
# Задача 7 Определители 3х3
import numpy as np

a1 = np.array([4, 5, 0])
a2 = np.array([2, 0, 4])
a3 = np.array([0, 5, 2])

# Допишите код здесь.
a = np.array([a1, a2, a3])
a = a.T
det_a = np.linalg.det(a)
print("Матрица:")
print(a)
print("Определитель:")
print(det_a)

Матрица:
[[4 2 0]
 [5 0 5]
 [0 4 2]]
Определитель:
-99.99999999999996
